version: '2'
services:
    fassas-app:
        image: fassas
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://fassas-postgresql:5432/fassas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fassas-postgresql:
        extends:
            file: postgresql.yml
            service: fassas-postgresql
