version: '2'
services:
    fassas-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/fassas/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=fassas
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
